config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :yfcases do
	resources :subsigntrueas, :controller => "yfcase_subsigntruea"
	resources :subsigntruebs, :controller => "yfcase_subsigntrueb"
	resources :subsigntruecs, :controller => "yfcase_subsigntruec"
  	resources :objectbuilds do 
		resources :plusrateas, :controller => "objectbuild_plusrateas"
		resources :plusratebs, :controller => "objectbuild_plusratebs"
		member do
			get :editplusratea, :controller => "yfcase_objectbuilds"
			get :editplusrateb, :controller => "yfcase_objectbuilds"
			patch :updateplusratea , :controller => "yfcase_objectbuilds"
			patch :updateplusrateb , :controller => "yfcase_objectbuilds"
			delete :deleteplusratea , :controller => "yfcase_objectbuilds" #刪除加成人員A及加成A
			delete :deleteplusrateb , :controller => "yfcase_objectbuilds" #刪除加成人員B及加成B
			delete :deleteplusrateall , :controller => "yfcase_objectbuilds" #刪除所有加成人員及加成
		end
	end
	member do
		get :yfratingscale #YF評量表
		get :deedtax #契稅申請書
		get :realestateregistration #不動產登記
		get :complaint #訴訟狀
		get :letter #存証信函
		get :commonpropertydivision #共有物分割
		# get :sendmail #寄發信件給會計
		delete :delete_subsigntruea #刪除副署人員1
		delete :delete_subsigntrueb #刪除副署人員2
		delete :delete_subsigntruec #刪除副署人員3
		
	end
  end
  root to: "yfcases#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/yfcases_controller.rb
class YfcasesController < ApplicationController
  include ApplicationHelper
  before_action :set_yfcase, only: [:edit, :update]
  before_action :show_helper, only: [:edit, :update, :destroy, :deedtax, :yfratingscale, :realestateregistration, :complaint, :letter]
  before_action :authenticate_user!

  # GET /yfcases
  # GET /yfcases.json
  def index
    prepare_variable_for_index_template
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template:'yfcases/reporte', pdf: 'Reporte'}
    end
  end

  # GET /yfcases/1
  # GET /yfcases/1.json
  def show
    @yfcase = Yfcase.find(params[:id])
    # 地坪總面積 (平方公尺)
    @landtotalarea = @yfcase.lands.map{ |n| [n.land_area.to_f * (n.land_holding_point_personal.to_f / n.land_holding_point_all.to_f)] }.flatten.sum
    
    # 建坪
    
    if @yfcase.builds.where("build_type_use = ?","0公設").present?
      # 找到第一筆非公設(notPU)的個人持分(build_holding_point_personal)
      @notPU_HP_personal=@yfcase.builds.where.not("build_type_use = ?","0公設").first.build_holding_point_personal
      # 找到第一筆非公設(notPU)的個人持分(build_holding_point_all)
      @notPU_HP_all=@yfcase.builds.where.not("build_type_use = ?","0公設").first.build_holding_point_all
      # 建坪總面積 (平方公尺)-有公設 (計算"0公設"的總面積)
      @withBuildTotalArea = @yfcase.builds.where("build_type_use = ?","0公設").map { |n| [n.build_area.to_f * ((n.build_holding_point_personal.to_f * @notPU_HP_personal.to_f) / (n.build_holding_point_all.to_f * @notPU_HP_all.to_f))] }.flatten.sum 
    else
      @withBuildTotalArea = 0
    end
    
    if @yfcase.builds.where("build_type_use = ?","12增建(持分後坪數打對折)").count >0
      # 建坪總面積 (平方公尺)-有增建 (計算"12增建(持分後坪數打對折)"的總面積)
      @addBuildTotalArea = @yfcase.builds.where("build_type_use = ?","12增建(持分後坪數打對折)").map { |n| [n.build_area.to_f * ((n.build_holding_point_personal.to_f) / (n.build_holding_point_all.to_f))] }.flatten.sum * 0.5
    else
      @addBuildTotalArea = 0
    end
    
    if @yfcase.builds.where.not("build_type_use = ? OR build_type_use = ?", "0公設","12增建(持分後坪數打對折)").count > 0
      # 建坪總面積 (平方公尺)-無公設 (計算不含"0公設"及"12增建(持分後坪數打對折)"的總面積)
      @withoutBuildTotalArea = @yfcase.builds.where.not("build_type_use = ? OR build_type_use = ?", "0公設","12增建(持分後坪數打對折)").map { |n| [n.build_area.to_f * (n.build_holding_point_personal.to_f / n.build_holding_point_all.to_f)] }.flatten.sum 
    else
      @withoutBuildTotalArea = 0
    end 
    
    # 坪價(萬)
    @pingprice1 = @yfcase.floor_price_1.to_f / ((@withoutBuildTotalArea+@withBuildTotalArea+@addBuildTotalArea)*0.3025).to_f
    @pingprice2 = @yfcase.floor_price_2.to_f / ((@withoutBuildTotalArea+@withBuildTotalArea+@addBuildTotalArea)*0.3025).to_f
    @pingprice3 = @yfcase.floor_price_3.to_f / ((@withoutBuildTotalArea+@withBuildTotalArea+@addBuildTotalArea)*0.3025).to_f
    @pingprice4 = @yfcase.floor_price_4.to_f / ((@withoutBuildTotalArea+@withBuildTotalArea+@addBuildTotalArea)*0.3025).to_f

    # 時價(萬)

    marketpricecount = @yfcase.objectbuilds.count
    marketpricesum=@yfcase.objectbuilds.map { |n| [(testvalue(n.total_price.to_f / n.build_area.to_f ,n.plusa,n.plusb))] }.flatten
    @marketprice = marketpricesum.map!{|e| e.to_f}.sum.fdiv(marketpricesum.size)
    respond_to do |format|
    format.html
    format.json
    format.pdf {render template:'yfcases/deedtax', pdf: 'Deedtax'}
    end
    # respond_to do |format|
    # format.html
    #   format.pdf do 
    #     pdf = YfcasePdf.new(@yfcase)
    #     send_data pdf.render, 
    #     filename: "yfcase_#{@yfcase.case_number}.pdf",
    #     type: "application/pdf",
    #     disposition: "inline"
    #   end
    # end 
  end

  # GET /yfcases/new
  def new
    @yfcase = current_user.yfcases.build( \
    floor_price_1:0,floor_price_2:0,floor_price_3:0,floor_price_4:0,number_of_attached_quantity_1:0,\
    number_of_attached_quantity_2:0,number_of_attached_quantity_3:0,deedtaxTransferPrice:0,deedtaxUnderreportedDays:0)
    @yfcase.final_decision ||= "未判定"
  end

  # GET /yfcases/1/edit
  def edit
  end

  # POST /yfcases
  # POST /yfcases.json
  def create
    @yfcase = current_user.yfcases.build(yfcase_params)
    @yfcase.user=current_user
    respond_to do |format|
      if @yfcase.save
        format.html { redirect_to @yfcase, notice: 'Yfcase was successfully created.' }
        format.json { render :show, status: :created, location: @yfcase }
      else
        format.html { render :new }
        format.json { render json: @yfcase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yfcases/1
  # PATCH/PUT /yfcases/1.json
  def update
    respond_to do |format|
      if @yfcase.update(yfcase_params)
        format.html { redirect_to @yfcase, notice: 'Yfcase was successfully updated.' }
        format.json { render :show, status: :ok, location: @yfcase }
      else
        format.html { render :edit }
        format.json { render json: @yfcase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yfcases/1
  # DELETE /yfcases/1.json
  def destroy
    @yfcase = Yfcase.find(params[:id])
    @yfcase.destroy
    respond_to do |format|
      format.html { redirect_to yfcases_url, notice: 'Yfcase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def yfratingscale
    @yfcase = Yfcase.find(params[:id])
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template:'yfcases/yfratingscale', pdf: 'Yfratingscale'}
    end
  end

  def deedtax
    @yfcase = Yfcase.find(params[:id])
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template:'yfcases/deedtax', pdf: 'Deedtax'}
    end
  end

  def realestateregistration
    @yfcase = Yfcase.find(params[:id])
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template:'yfcases/realestateregistration', pdf: 'Realestateregistration',orientation: 'Landscape'}
    end
  end

  def complaint
    @yfcase = Yfcase.find(params[:id])
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template:'yfcases/complaint', pdf: 'Complaint'}
    end
  end
  
  def letter
    @yfcase = Yfcase.find(params[:id])
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template:'yfcases/letter', pdf: 'Letter'}
    end    
  end
  
  def commonpropertydivision
    @yfcase = Yfcase.find(params[:id])
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template:'yfcases/commonpropertydivision', pdf: 'Commonpropertydivision'}
    end    
  end

  def delete_subsigntruea
    @yfcase = Yfcase.find(params[:id])
    @subsigntruea_delete= @yfcase.subsigntrueas.first
    @subsigntruea_delete.destroy
    redirect_to @yfcase
  end

  def delete_subsigntrueb
    @yfcase = Yfcase.find(params[:id])
    @subsigntrueb_delete= @yfcase.subsigntruebs.first
    @subsigntrueb_delete.destroy
    redirect_to @yfcase
  end

  def delete_subsigntruec
    @yfcase = Yfcase.find(params[:id])
    @subsigntruec_delete= @yfcase.subsigntruecs.first
    @subsigntruec_delete.destroy
    redirect_to @yfcase
  end
  
  def sendmail
    ContactMailer.say_hello_to().deliver_now
    redirect_to @yfcase, notice: 'User was successfully created.'
  end


  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yfcase
      @yfcase = current_user.yfcases.find(params[:id])
    end

    def show_helper
      @yfcase = Yfcase.find(params[:id])
      # 地坪總面積 (平方公尺)
      @landtotalarea = @yfcase.lands.map{ |n| [n.land_area.to_f * (n.land_holding_point_personal.to_f / n.land_holding_point_all.to_f)] }.flatten.sum
      
      # 建坪
      
      if @yfcase.builds.where("build_type_use = ?","0公設").present?
        # 找到第一筆非公設(notPU)的個人持分(build_holding_point_personal)
        @notPU_HP_personal=@yfcase.builds.where.not("build_type_use = ?","0公設").first.build_holding_point_personal
        # 找到第一筆非公設(notPU)的個人持分(build_holding_point_all)
        @notPU_HP_all=@yfcase.builds.where.not("build_type_use = ?","0公設").first.build_holding_point_all
        # 建坪總面積 (平方公尺)-有公設 (計算"0公設"的總面積)
        @withBuildTotalArea = @yfcase.builds.where("build_type_use = ?","0公設").map { |n| [n.build_area.to_f * ((n.build_holding_point_personal.to_f * @notPU_HP_personal.to_f) / (n.build_holding_point_all.to_f * @notPU_HP_all.to_f))] }.flatten.sum 
      else
        @withBuildTotalArea = 0
      end
      
      if @yfcase.builds.where("build_type_use = ?","12增建(持分後坪數打對折)").count >0
        # 建坪總面積 (平方公尺)-有增建 (計算"12增建(持分後坪數打對折)"的總面積)
        @addBuildTotalArea = @yfcase.builds.where("build_type_use = ?","12增建(持分後坪數打對折)").map { |n| [n.build_area.to_f * ((n.build_holding_point_personal.to_f) / (n.build_holding_point_all.to_f))] }.flatten.sum * 0.5
      else
        @addBuildTotalArea = 0
      end
      
      if @yfcase.builds.where.not("build_type_use = ? OR build_type_use = ?", "0公設","12增建(持分後坪數打對折)").count > 0
        # 建坪總面積 (平方公尺)-無公設 (計算不含"0公設"及"12增建(持分後坪數打對折)"的總面積)
        @withoutBuildTotalArea = @yfcase.builds.where.not("build_type_use = ? OR build_type_use = ?", "0公設","12增建(持分後坪數打對折)").map { |n| [n.build_area.to_f * (n.build_holding_point_personal.to_f / n.build_holding_point_all.to_f)] }.flatten.sum 
      else
        @withoutBuildTotalArea = 0
      end 
      
      # 坪價(萬)
      @pingprice1 = @yfcase.floor_price_1.to_f / ((@withoutBuildTotalArea+@withBuildTotalArea+@addBuildTotalArea)*0.3025).to_f
      @pingprice2 = @yfcase.floor_price_2.to_f / ((@withoutBuildTotalArea+@withBuildTotalArea+@addBuildTotalArea)*0.3025).to_f
      @pingprice3 = @yfcase.floor_price_3.to_f / ((@withoutBuildTotalArea+@withBuildTotalArea+@addBuildTotalArea)*0.3025).to_f
      @pingprice4 = @yfcase.floor_price_4.to_f / ((@withoutBuildTotalArea+@withBuildTotalArea+@addBuildTotalArea)*0.3025).to_f

      # 時價(萬)

      marketpricecount = @yfcase.objectbuilds.count

app/helpers/yfcases_helper.rb
module YfcasesHelper
end

app/views/yfcases/partials/_baseData.html.erb
<tr>
  <th style="width:10%;">案號</th>
  <td style="width:30%;">
    <%= @yfcase.case_number %>
  </td>
  <th style="width:10%;">債務人</th>
  <td style="width:25%;">
    <%= @yfcase.debtorName %>
  </td>
  <th style="width:10%;">債權人</th>
  <td><%= @yfcase.creditorName.blank? ? @yfcase.company : @yfcase.creditorName %></td>
  </tr>
  <tr>
  <th>住址</th>
  <td colspan="5">
    <%= @yfcase.township.try(:zip_code) %> <%= @yfcase.country.try(:name) %><%= @yfcase.township.try(:name) %><%= @yfcase.other_address %>
  </td>
</tr>

app/views/yfcases/partials/_buildCheckList.html.erb
<tr>
  <th style="width:6%;">結果</th>
  <th style="width:21%;">查檢內容</th>
  <th style="width:6%;">結果</th>
  <th>查檢內容</th>
  <th style="width:6%;">結果</th>
  <th style="width:15%;">查檢內容</th>
  <th style="width:6%;">結果</th>
  <th style="width:19%;">查檢內容</th>
</tr>
<!-- 第一行 -->
<tr>
  <td><%= @yfcase.occupy ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">01.占用鄰地？</th>
  <td><%= @yfcase.rent ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">05.出租/出借/佔用？</th>
  <td><%= @yfcase.vegetable_market ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">09.鄰近菜市場？</th>
  <td><%= @yfcase.post_office ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">13.鄰近郵局/機關？</th>
</tr>

<!-- 第二行 -->
<tr>
  <td><%= @yfcase.register ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">02.無未保存登記建物？</th>
  <td><%= @yfcase.leak ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">06.無嚴重漏水現象？</th>
  <td><%= @yfcase.supermarket ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">10.鄰近大賣場？</th>
  <td><%= @yfcase.main_road ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">14.鄰近幹道？</th>
</tr>
<!-- 第三行 -->
<tr>
  <td><%= @yfcase.parking_space ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">03.停車位(機車/汽車)？</th>
  <td><%= @yfcase.easy_parking ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">07.停車方便？</th>
  <td><%= @yfcase.school ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">11.鄰近學校？</th>
  <td><%= @yfcase.water_and_power_failure ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">15.斷水斷電？</th>
</tr>
<!-- 第四行 -->
<tr>
  <td><%= @yfcase.management_fee ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">04.積欠管理費？</th>
  <td><%= @yfcase.railway ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">08.鄰近捷運站/台鐵站？</th>
  <td><%= @yfcase.park ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">12.鄰近公園？</th>
  <td><%= @yfcase.good_vision ? "V" : "" %></td>
  <th class="yfratingscalePDFBuildCheckListItem">16.採光視野良好？</th>
</tr>
<!-- 備註 -->
<tr>
  <th>備註</th>
  <td colspan="7"></td>
</tr>

app/views/yfcases/partials/_finalDecision.html.erb
<tr>
    <!-- 區域負責人 -->
    <% yfcasefullname = @yfcase.user.first_name + @yfcase.user.last_name %>
    <!-- 區域負責人:管轄區域 -->
    <% yfcaseworkarea = @yfcase.user.userWorkArea %>
    <!-- 登入人員 -->
    <% currentfullname = current_user.first_name + current_user.last_name %>
    <!-- 登入人員:管轄區域 -->
    <% currentworkarea = current_user.userWorkArea %>
    <!-- 副署人員1 -->
    <% @yfcase.subsigntrueas.first.blank? ? ' ' : subsigntrueafullname = @yfcase.subsigntrueas.first.signtruea %>
    <!-- 副署人員2 -->
    <% @yfcase.subsigntruebs.first.blank? ? ' ' : subsigntruebfullname = @yfcase.subsigntruebs.first.signtrueb %>
    <!-- 副署人員3 -->
    <% @yfcase.subsigntruecs.first.blank? ? ' ' : subsigntruecfullname = @yfcase.subsigntruecs.first.signtruec %>
    <!-- 副署人員1:管轄區域 -->
    <% @yfcase.subsigntrueas.first.blank? ? ' ' : subsigntrueaworkarea = @yfcase.subsigntrueas.first.signtruea_work_area %>
    <!-- 副署人員2:管轄區域 -->
    <% @yfcase.subsigntruebs.first.blank? ? ' ' : subsigntruebworkarea = @yfcase.subsigntruebs.first.signtrueb_work_area %>
    <!-- 副署人員3:管轄區域 -->
    <% @yfcase.subsigntruecs.first.blank? ? ' ' : subsigntruecworkarea = @yfcase.subsigntruecs.first.signtruec_work_area %>
    <th style="width:28%;">結論</th>
    <th style="width:18%;">區域負責人</th>
    <th style="width:18%;">
      
      <!--登入人員=管理者 或是 (副署人員1有資料+區域負責人=登入人員) >> 顯示"副署人員+刪除鈕"-->
        <% if current_user.role == 1 || (@yfcase.subsigntrueas.first.present? && yfcasefullname == currentfullname) %>
          副署人員1
          <%= link_to "刪除", delete_subsigntruea_yfcase_path(@yfcase),method: :delete,class: "btn btn-info btn-sm" %>
        <% elsif @yfcase.final_decision.blank? || (@yfcase.final_decision.present? && yfcaseworkarea == currentworkarea) %>
          <span style="color:red;"><%= '該區已副署' %></span>
        <% else %>
          <% if @yfcase.subsigntrueas.first.blank? %>
            <%= link_to "副署人員1", new_yfcase_subsigntruea_path(@yfcase),class: "btn btn-primary btn-sm" %>
          <% else %>
            <%= "副署人員1" %>
          <% end %>
        <% end %>
    </th>
    <th style="width:18%;">
        <% if current_user.role == 1 || (@yfcase.subsigntruebs.first.present? && yfcasefullname == currentfullname) %>
          副署人員2
          <%= link_to "刪除", delete_subsigntrueb_yfcase_path(@yfcase),method: :delete,class: "btn btn-info btn-sm" %>
        <% elsif @yfcase.final_decision.blank? || (@yfcase.final_decision.present? && yfcaseworkarea == currentworkarea) %>
          <span style="color:red;"><%= '該區已副署' %></span>
        <% elsif @yfcase.final_decision.present? && yfcaseworkarea != currentworkarea && subsigntrueaworkarea == currentworkarea %>
          <span style="color:red;"><%= '該區已副署' %></span>
        <% else %>
          <% if @yfcase.subsigntruebs.first.blank? && @yfcase.subsigntrueas.first.present? %>
            <%= link_to "副署人員2", new_yfcase_subsigntrueb_path(@yfcase),class: "btn btn-primary btn-sm" %>
          <% else %>
            <%= "副署人員2" %>
          <% end %>
        <% end %>
    </th>
    
    <th>
        <% if current_user.role == 1 || (@yfcase.subsigntruecs.first.present? && yfcasefullname == currentfullname) %>
          副署人員3
          <%= link_to "刪除", delete_subsigntruec_yfcase_path(@yfcase),method: :delete,class: "btn btn-info btn-sm" %>
        <% elsif  @yfcase.final_decision.blank? || (@yfcase.final_decision.present? && yfcaseworkarea == currentworkarea) %>
          <span style="color:red;"><%= '該區已副署' %></span>
        <% elsif @yfcase.final_decision.present? && yfcaseworkarea != currentworkarea && ((subsigntrueaworkarea == currentworkarea && subsigntruebworkarea != currentworkarea) || (subsigntrueaworkarea != currentworkarea && subsigntruebworkarea == currentworkarea)) %>
          <span style="color:red;"><%= '該區已副署' %></span>
        <% else %>
          <% if @yfcase.subsigntruecs.first.blank? && @yfcase.subsigntruebs.first.present? %>
            <%= link_to "副署人員3", new_yfcase_subsigntruec_path(@yfcase),class: "btn btn-primary btn-sm" %>
          <% else %>
            <%= "副署人員3" %>
          <% end %>
        <% end %>
    </th>
</tr>


<tr>
  <td>
    <% if @yfcase.final_decision == "1拍進場" %>
    <div class="yfratingscalePDFFinaldecisionJudgment" style="color:Brown;border:5px solid Brown;">
        <%= @yfcase.final_decision %>
    </div>
    <% elsif @yfcase.final_decision == "2拍進場" %>
    <div class="yfratingscalePDFFinaldecisionJudgment" style="color:purple;border:5px solid purple;">
        <%= @yfcase.final_decision %>
    </div>
    <% elsif @yfcase.final_decision == "3拍進場" %>
    <div class="yfratingscalePDFFinaldecisionJudgment" style="color:blue;border:5px solid blue;">
        <%= @yfcase.final_decision %>
    </div>
    <% elsif @yfcase.final_decision == "4拍進場" %>
    <div class="yfratingscalePDFFinaldecisionJudgment" style="color:green;border:5px solid green;">
        <%= @yfcase.final_decision %>
    </div>
    <% elsif @yfcase.final_decision == "放棄" %>
    <div class="yfratingscalePDFFinaldecisionJudgment" style="color:red;border:5px solid red;">
        <%= @yfcase.final_decision %>
    </div>
    <% else %>
    <%= "" %>
    <% end %>
  </td>
  <td class="yfratingscalePDFPerson">
    <div class="yfratingscalePDFPersonCircle">
      <table class="yfratingscalePDFPersonTable">
        <tr>
          <td class="yfratingscalePDFPersonName" style="border-bottom:5px solid red;">
            <%= @yfcase.user.first_name %><%= @yfcase.user.last_name %>
          </td>
        </tr>
        <tr>
          <td class="yfratingscalePDFPersonDate">
            <%= @yfcase.final_decision_date.blank? ? '待結論判定' : @yfcase.final_decision_date %>
          </td>
        </tr>
        <tr>
          <td class="yfratingscalePDFPersonName"style="border-top:5px solid red;">
            <%= @yfcase.user.userWorkArea %>
          </td>
        </tr>
      </table>
    </div>
  </td>
    
    
  <td class="yfratingscalePDFPerson">
    <% if @yfcase.subsigntrueas.first.present? %>
      <div class="yfratingscalePDFPersonCircle">
        <table class="yfratingscalePDFPersonTable">
          <tr>
            <td class="yfratingscalePDFPersonName" style="border-bottom:5px solid red;">
              <%= @yfcase.subsigntrueas.first.signtruea_first_name %><%= @yfcase.subsigntrueas.first.signtruea_last_name %>
            </td>
          </tr>
          <tr>
            <td class="yfratingscalePDFPersonDate">
              <%= @yfcase.subsigntrueas.first.signtruea_date %>
            </td>
          </tr>
          <tr>
            <td class="yfratingscalePDFPersonName"style="border-top:5px solid red;">
              <%= @yfcase.subsigntrueas.first.signtruea_work_area %>
            </td>
          </tr>
        </table>
      </div>
     <% end %> 
    </td>
    
    
    <td class="yfratingscalePDFPerson">
    <% if @yfcase.subsigntruebs.first.present? %>
      <div class="yfratingscalePDFPersonCircle">
        <table class="yfratingscalePDFPersonTable">
          <tr>
            <td class="yfratingscalePDFPersonName" style="border-bottom:5px solid red;">
              <%= @yfcase.subsigntruebs.first.signtrueb_first_name %><%= @yfcase.subsigntruebs.first.signtrueb_last_name %>
            </td>
          </tr>
          <tr>
            <td class="yfratingscalePDFPersonDate">
              <%= @yfcase.subsigntruebs.first.signtrueb_date %>
            </td>
          </tr>
          <tr>
            <td class="yfratingscalePDFPersonName"style="border-top:5px solid red;">
              <%= @yfcase.subsigntruebs.first.signtrueb_work_area %>
            </td>
          </tr>
        </table>
      </div>
     <% end %> 
    </td>
    
    <td class="yfratingscalePDFPerson">
    <% if @yfcase.subsigntruecs.first.present? %>
      <div class="yfratingscalePDFPersonCircle">
        <table class="yfratingscalePDFPersonTabe">
          <tr>
            <td class="yfratingscalePDFPersonName" style="border-bottom:5px solid red;">
              <%= @yfcase.subsigntruecs.first.signtruec_first_name %><%= @yfcase.subsigntruecs.first.signtruec_last_name %>
            </td>
          </tr>
          <tr>
            <td class="yfratingscalePDFPersonDate">
              <%= @yfcase.subsigntruecs.first.signtruec_date %>
            </td>
          </tr>
          <tr>
            <td class="yfratingscalePDFPersonName"style="border-top:5px solid red;">
              <%= @yfcase.subsigntruecs.first.signtruec_work_area %>
            </td>
          </tr>
        </table>
      </div>
     <% end %> 
    </td>
    
</tr>